terratex_reallife/ENVIRO/stadthalle/markler/markler_client.lua
=>  spelling mistakes fixed

terratex_reallife/ENVIRO/inventar_new/mobilephone/mobile_old.lua
Anzeige über showError bei Taxi-Ruf
=> Taxi-Ruf Anzeige in Error-Box

terratex_reallife/ENVIRO/inventar_new/mobilephone/mobile_old.lua
Änderung der Mechaniker-Job-Marker-Farbe zu einem Türkis
=> Mechaniker-Job-Marker-Farbe

terratex_reallife/ENVIRO/jobs/flug/flug_marker.lua, terratex_reallife/MAPS/umgebung/flugjob_helipad.map, terratex_reallife/meta.xml
Anderer Marker für Helis beim Abgeben + Kleine Bodenveränderung + Helimarkierung
=> Anderer Marker für Helis beim Abgeben

terratex_reallife/ENVIRO/shops/24_7_shop_client.lua
Fixxen der Beschreibungen des 24/7
=> Beschreibungen 24/7

terratex_reallife/ENVIRO/jobs/lkw/lieferanten_marker.lua
Sichertheiten mit Kaution ersetzt.
Ein oder andere Tippfehler behoben.
=> Fixed some typos

terratex_reallife/ENVIRO/jobs/lkw/lieferanten_marker.lua
Nachricht beim Abgeben eines Trucks korrigiert.
=> Small Typo again.

terratex_reallife/ENVIRO/fraktionen/lspd/arrest.lua
Kleine Schreibfehler ausgebessert.
=> Kleine Schreibfehler ausgebessert.

terratex_reallife/ENVIRO/fraktionen/lspd/lspdcars.lua, terratex_reallife/ENVIRO/specialCars/abschleppTruck/abschleppTruck_client.lua, terratex_reallife/ENVIRO/specialCars/abschleppTruck/abschleppTruck_server.lua, terratex_reallife/SYSTEM/vehsys/fahrzeug_gui.lua, terratex_reallife/meta.xml
Generell funktioniert dieser Abschlepper für jeden Spieler (Für zukünftige Gedanken).
(So kann der User zum Beispiel sein eigenes Boot(Dinghy) aufladen und über die Map fahren)
Aktuell wird der Truck aber nur für das SAPD gespawnt.
Ein Fahrzeug kann aufgeladen werden, indem man im Abschlepp-Truck sitzt, auf das aufzuladene Fahrzeug klickt und den Button "Aufladen" klickt.
Abgeladen werden kann das Fahrzeug durch einen Klick auf den Abschlepp-Truck und den Button "Abladen". Anschließend wird eine Client-Vorschau angezeigt, in der man das abzuladene Fahrzeug mit dem Cursor in der Welt und einem Radius von 8 zum Abschlepp-Truck bewegen kann. Wird das Fahrzeug mit einem Mausklick platziert, so wird das Fahrzeug abgeladen und an die ausgewählte Stelle gesetzt. Die Vorschau kann durch einen …
=> Abschlepp-Truck

terratex_reallife/SYSTEM/vehsys/vehicle_pcolor_client.lua
- Vorschau für /pcolor
- Leichte Verbesserung der GUI
- Typos
=> /pcolor Vorschau

terratex_reallife/ADMINSYSTEM/teleports.lua
What is this Pullrequest about?
Davor konnte man /gp ORT und /gj ID nicht in einem Fahrzeug ausführen.
Früher habe ich mich sehr oft auf meinem eigenen Server zu Orten teleportiert, daher war das für mich wichtig. Könnte daher auch für andere Administratoren wichtig sein. ^^
Are there any Issue Tickets related to this request?
%
What are the changes you did here?
you can make /gp and /gj in vehicles now. (ist übrigens komplett getestet! :))
=> /gp, /gj in vehicles

terratex_reallife/ENVIRO/ruhezone/ruhezone_client.lua
=> Fixes #172

terratex_reallife/ENVIRO/fraktionen/taxi/taxi_vehicles.lua
What is this Pullrequest about?
Du kannst nun nicht mehr als Zivilist ein Taxiauto klauen.
Are there any Issue Tickets related to this request?
#178 
What are the changes you did here?
zivis cannot enter taxiveh
=> zivis cannot enter taxiveh

terratex_reallife/SQLS/update.1.2.1.sql
=> Teleport-Bug Kino

terratex_reallife/ENVIRO/jobs/busfahrer/Fahrplan_client.lua, terratex_reallife/ENVIRO/jobs/busfahrer/busfahrer_server.lua, terratex_reallife/ENVIRO/jobs/busfahrer/haltestellen.lua
=> Busjob farbige Busse + Darstellung in Linienansicht

terratex_reallife/ENVIRO/fraktionen/lspd/lspdcars.lua
=> PD DFT nicht mehr zweimal im Polizeicomputer anzeigen

terratex_reallife/SYSTEM/vehsys/tankstelle.lua
What is this Pullrequest about?
Bezahlung beim Tanken #208
Es wird primär Bargeld verwendet. Wenn nicht genug Bargeld, wird Bank geprüft.
Bei Bankbezahlung werden 5% gebühren verrechnet
Are there any Issue Tickets related to this request?
* #208
What are the changes you did here?
* Es wird primär Bargeld verwendet. Wenn nicht genug Bargeld, wird Bank geprüft.
Bei Bankbezahlung werden 5% gebühren verrechnet
=> #208 bezahlung beim tanken

terratex_reallife/ENVIRO/shops/24_7_shop_client.lua, terratex_reallife/ENVIRO/shops/24_7_shop_server.lua
What is this Pullrequest about?
Preise im 24/7 richtig stellen
Are there any Issue Tickets related to this request?
* #207 
What are the changes you did here?
* Codedesign & behebung des Problems mit den falsch angezeigten Preisen.
=> #207 preise 24 7

terratex_reallife/SYSTEM/vehsys/vehicle_pcolor.lua, terratex_reallife/SYSTEM/vehsys/vehicle_pcolor_client.lua
=> /pcolor Vorschau "zu wenig Geld"-Bug

terratex_reallife/USEFULL_SCRIPTS/garageFunctions.lua, terratex_reallife/meta.xml
Garagentore, die sich über setGarageOpen steuern lassen und isGarageOpen abfragen lassen.
Erstellen mit createGarage.
=> Garagentore

terratex_reallife/ENVIRO/interiors/24_7.lua, terratex_reallife/ENVIRO/shops/24_7_shop_server.lua
Es können nun auch andere 24/7 Interiors gesetzt werden + Neue Position des 24/7 Markers für neue Tankstelle
=> 24/7 andere Interiors setzbar für kleinere Gebäude

terratex_reallife/ENVIRO/specialCars/abschleppTruck/abschleppTruck_client.lua, terratex_reallife/ENVIRO/specialCars/abschleppTruck/abschleppTruck_server.lua
=> Bugfix DFT

terratex_reallife/ENVIRO/interiors/24_7.lua
Ka warum es auf einmal nicht mehr mit meinen alten Koordinaten funktioniert hat. Sollte jetzt funktionieren.
=> Fix 24/7 Tankstelle LS<->LV

terratex_reallife/ENVIRO/baustellen.lua
Da Ceeser und ich in Zukunft mehr Baustellen einbauen wollen, fanden wir es etwas willkürlich, wenn der Server statistisch gesehen immer mehr Baustellen auswählt. Somit habe ich mir mal die Mühe gemacht und für das ganze eine e-Funktion aufgestellt und noch ein paar Script-Änderungen gemacht.
Wahrscheinlichkeiten für die Anzahl der Baustellen (mit aktuellen 11) (Ungefähr)
https://puu.sh/qRTdn/0157395952.png
Als Graph:
https://puu.sh/qRQuO/6c86a4dadd.png
=> Neue Formel zur Bestimmung der Anzahl der Baustellen

terratex_reallife/ENVIRO/baustellen.lua
Kleine Verbesserung (Wahrscheinlichkeit für eine Baustelle zu hoch)
=> Verbesserung Wahrscheinlichkeiten Baustellen

terratex_reallife/ENVIRO/spawn_kill_system/spawn.lua, terratex_reallife/SYSTEM/vehsys/loadprivcars.lua
=> Bugfix in Iterior reconnecten

terratex_reallife/ENVIRO/chat.lua
=> 11880 Direkt verbinden

terratex_reallife/ENVIRO/fraktionen/lspd/arrest.lua
=> Radius erhöhen /frisk /take

terratex_reallife/ENVIRO/fraktionen/lspd/spikes/spikes_client.lua, terratex_reallife/ENVIRO/fraktionen/lspd/spikes/spikes_server.lua, terratex_reallife/meta.xml
=> Nagelbänder

terratex_reallife/ENVIRO/fraktionen/lspd/spikes/spikes_server.lua
=> Nagelbänder-Meldung-Fix

terratex_reallife/ENVIRO/fraktionen/lspd/spikes/spikes_client.lua, terratex_reallife/ENVIRO/fraktionen/lspd/spikes/spikes_server.lua
=> Nagelband-Fix

Jenkinsfile
=> Only deploy for master branch

terratex_reallife/ENVIRO/fraktionen/medics/Medic_Command.lua, terratex_reallife/ENVIRO/fraktionen/medics/medics_cars.lua
=> Revision of the sanitary group, added new vehicles

terratex_reallife/ENVIRO/spawn_kill_system/spawn.lua
=> New spawnpoint for faction members medics

terratex_reallife/ENVIRO/fraktionen/taxi/taxi_vehicles.lua
=> Added new vehicles for taxi, reqeusting map-change taxibase

terratex_reallife/ENVIRO/fraktionen/taxi/taxi_vehicles.lua
=> Fix vehicles from taxi faction

terratex_reallife/ENGINE/mapFileAdditions/mapEditorScriptingExtension_s.lua
=> Fix map-changes from changelog.reloaded-1.0.1b.communityproject

terratex_reallife/ENVIRO/fraktionen/lspd/abschleppen.lua
=> Bugfix zu community.reloaded-1.0.2b

terratex_reallife/ENVIRO/fraktionen/medics/medics_cars.lua
=> Fix Koord for duty point medics ls

terratex_reallife/SYSTEM/vehsys/paynspray.lua
=> Fix PaynPray_LV

terratex_reallife/SYSTEM/vehsys/loadprivcars.lua, terratex_reallife/SYSTEM/vehsys/privCarCommands.lua
=> Fix vehicle_money

terratex_reallife/MAPS/umgebung/PaynPrayLV_neu.map, terratex_reallife/meta.xml
=> Add PaynSprayGarage_LV

terratex_reallife/ENVIRO/fraktionen/taxi/taxi_vehicles.lua
=> Fixed taxi-gate, koord issue

terratex_reallife/EVENTSCRIPS/chrismas/geschenke_geben.lua, terratex_reallife/meta.xml
=> add chrismas-script

package-lock.json, package.json, terratex_reallife/ENVIRO/fraktionen/grove/grovecars.lua, terratex_reallife/ENVIRO/fraktionen/lspd/abschleppen.lua, terratex_reallife/ENVIRO/fraktionen/lspd/crimesystem/CrimeSystem_definitions.lua, terratex_reallife/MAPS/fraktionsbase/grove_base.map, terratex_reallife/SYSTEM/scheinesys_vehicle.lua, terratex_reallife/meta.xml
- add isWaterPlane
- add grove base
- add new grove vehicles
- half-jailtime
@geramy92 Bitte wenn möglich, "isWaterPlane" überprüfen.
Bin mir nicht ganz sicher, ob ich es richtig eingestellt habe.
=> - add silvester

terratex_reallife/ENVIRO/fraktionen/lspd/GeldTransporter/GeldTransporter_Server.lua
=> Überarbeitung des Geldtransporters

terratex_reallife/meta.xml
=> Silvester christmas

terratex_reallife/ENVIRO/jobs/flug/flug_gui.lua
=> flug_gui.lua

terratex_reallife/ENVIRO/fraktionen/medics/medics_cars.lua
=> medics_cars.lua

terratex_reallife/ENVIRO/fraktionen/lspd/lspdcars.lua
balancing + delete bug sek vehicle
=> lspdcars.lua

terratex_reallife/SYSTEM/vehsys/paynspray.lua
=> paynspray.lua

terratex_reallife/ENVIRO/jobs/flug/flug_marker.lua
=> flug_marker.lua

terratex_reallife/ADMINSYSTEM/systems/isadmin.lua
=> fix formatting

terratex_reallife/ENVIRO/fraktionen/lspd/innendienst.lua, terratex_reallife/ENVIRO/jobs/flug/flug_gui.lua, terratex_reallife/ENVIRO/jobs/flug/flug_marker.lua, terratex_reallife/ENVIRO/terralapptapp/tictactoe_client.lua, terratex_reallife/SYSTEM/vehsys/landebahnen.lua
=> text changes

terratex_reallife/ADMINSYSTEM/general.lua
=> general.lua

terratex_reallife/ENVIRO/fraktionen/lspd/arrest.lua
=> arrest.lua

terratex_reallife/ENVIRO/jobs/detektiv/detektiv_commands.lua
=> detektiv_commands.lua

terratex_reallife/ADMINSYSTEM/fun_client.lua
=> fun_client.lua

terratex_reallife/ENVIRO/skins/skingui_client.lua
=> skingui_client.lua

terratex_reallife/SYSTEM/vehsys/privCarCommands.lua, terratex_reallife/SYSTEM/vehsys/privateVehicle/functions_server.lua, terratex_reallife/SYSTEM/vehsys/tankstelle.lua
=> Voice chat

terratex_reallife/ENVIRO/fraktionen/medics/medics_cars.lua
=> - rework Medic-Cars

terratex_reallife/ENGINE/mapFileAdditions/noOcclusionZones_client.lua
=> - Fix some noOcclusionZones (Taxi - Medic)

terratex_reallife/SYSTEM/haussys/hausscripts/geramy.lua
=> geramy.lua

terratex_reallife/ENVIRO/fraktionen/lls/lls_cars.lua
=> lls_cars.lua

terratex_reallife/ENVIRO/fraktionen/grove/grovecars.lua
- delete bikes
- delete helicopter
[edit here]
* [edit here]
=> delete bikes & helicopter

terratex_reallife/ENVIRO/fraktionen/grove/grovecars.lua
=> grovecars.lua

terratex_reallife/ENVIRO/stadthalle/markler/markler_server.lua
=> - change timer

terratex_reallife/SYSTEM/logging/debug_log_client.lua, terratex_reallife/SYSTEM/logging/debug_log_server.lua, terratex_reallife/SYSTEM/logging/json_logger.lua, terratex_reallife/SYSTEM/logging/logging_server_func.lua, terratex_reallife/SYSTEM/logging/loggingsys.lua, terratex_reallife/USEFULL_SCRIPTS/debug.lua, terratex_reallife/meta.xml
=> New debugs

terratex_reallife/ENVIRO/hufeisen/hufeisen.lua, terratex_reallife/ENVIRO/jobs/pay_skill_sys.lua, terratex_reallife/EVENTSCRIPS/ostern/ostern_server.lua, terratex_reallife/SYSTEM/goldsystem/gold_client.lua, terratex_reallife/SYSTEM/goldsystem/gold_helper.lua, terratex_reallife/SYSTEM/goldsystem/gold_server.lua, terratex_reallife/SYSTEM/train.lua, terratex_reallife/UI/Gold.html, terratex_reallife/USER/userdata/player_connect.lua, terratex_reallife/USER/userdata/save_data.lua, terratex_reallife/static_script_config.lua
=> MTA:SA 1.3.4

terratex_reallife/ENVIRO/fraktionen/respawn_functions.lua, terratex_reallife/ENVIRO/hufeisen/hufeisen.lua, terratex_reallife/SQLS/updates.sql, terratex_reallife/SYSTEM/goldsystem/gold_server.lua, terratex_reallife/USER/payday/updateplaytime.lua, terratex_reallife/static_script_config.lua
=> bugfix 1.3.5

terratex_reallife/ENGINE/mysql/mysql.lua, terratex_reallife/EVENTSCRIPS/ostern/ostern_server.lua
=> fix easter

terratex_reallife/SYSTEM/logging/logging_server_func.lua
=> fix logging

terratex_reallife/ENGINE/mysql/mysql.lua
=> fix mysql 2

terratex_reallife/ENVIRO/fraktionen/taxi/taxi_vehicles.lua
=> taxi_vehicles
